// Auto-generated by generate_voiceover.mjs — narration durations in seconds.
export const VO = {
  "scene01": 13.45,
  "scene02": 13.32,
  "scene03": 13.45,
  "scene04": 11.52,
  "scene05": 16.14,
  "scene06": 8.96,
  "scene07": 18.29,
  "scene08": 14.94,
  "scene09": 10.71,
  "scene10": 15.31,
  "scene11": 9.8
};
