#!/usr/bin/env python3
"""
build_mapping_spec_xlsx.py — render the SDTM mapping specification as an Excel workbook.

Mirrors mapping_specification.md in the format mapping specs are actually maintained
in industry: one sheet per domain, variable-level rows, plus CT and QC sheets.

Run: python3 build_mapping_spec_xlsx.py   ->  SDTM_Mapping_Specification.xlsx
"""

import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "SDTM_Mapping_Specification.xlsx")

# ---- house style -----------------------------------------------------------
FONT = "Arial"
INK = "0F2E3D"; TEAL = "0E7C86"; ACCENT = "E8833A"; PAPER = "F3F7F8"; LINE = "CFDEE1"
H_FILL = PatternFill("solid", fgColor=INK)
SUB_FILL = PatternFill("solid", fgColor=TEAL)
BAND = PatternFill("solid", fgColor=PAPER)
WARN_FILL = PatternFill("solid", fgColor="FDF1E7")
THIN = Side(style="thin", color=LINE)
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

def style_header(ws, row, ncols, fill=H_FILL):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(name=FONT, bold=True, color="FFFFFF", size=10)
        cell.fill = fill
        cell.alignment = Alignment(vertical="center", horizontal="left", wrap_text=True)
        cell.border = BORDER
    ws.row_dimensions[row].height = 30

def write_table(ws, start_row, headers, rows, widths, band=True):
    for i, h in enumerate(headers, start=1):
        ws.cell(row=start_row, column=i, value=h)
    style_header(ws, start_row, len(headers))
    for r, rowvals in enumerate(rows, start=start_row + 1):
        for c, v in enumerate(rowvals, start=1):
            cell = ws.cell(row=r, column=c, value=v)
            cell.font = Font(name=FONT, size=10)
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = BORDER
            if band and (r - start_row) % 2 == 0:
                cell.fill = BAND
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = ws.cell(row=start_row + 1, column=1)
    ws.auto_filter.ref = (f"A{start_row}:{get_column_letter(len(headers))}"
                          f"{start_row + len(rows)}")

def title_block(ws, title, subtitle=None):
    ws["A1"] = title
    ws["A1"].font = Font(name=FONT, bold=True, size=14, color=INK)
    if subtitle:
        ws["A2"] = subtitle
        ws["A2"].font = Font(name=FONT, italic=True, size=10, color="5A7682")

wb = Workbook()

# ============================================================ COVER
ws = wb.active; ws.title = "Cover"
ws.sheet_view.showGridLines = False
ws["A1"] = "SDTM Mapping Specification"
ws["A1"].font = Font(name=FONT, bold=True, size=20, color=INK)
ws["A2"] = "Study ABC-01  ·  synthetic training data"
ws["A2"].font = Font(name=FONT, size=12, color=TEAL)

meta = [
    ("Study", "ABC-01 (synthetic)"),
    ("Design", "Phase 2, Drug A 50 mg vs Placebo, oral once daily, ~4 weeks"),
    ("Population", "8 subjects across 2 sites"),
    ("Standard", "SDTMIG v3.3"),
    ("Purpose", "Specifies how the raw EDC-style CSVs map to SDTM datasets"),
    ("Source data", "/data/*_raw.csv"),
    ("Target data", "/data/sdtm/*.csv"),
    ("Generated by", "build_mapping_spec_xlsx.py (regenerate to update)"),
]
r = 4
for k, v in meta:
    ws.cell(row=r, column=1, value=k).font = Font(name=FONT, bold=True, size=10, color=INK)
    ws.cell(row=r, column=2, value=v).font = Font(name=FONT, size=10)
    r += 1

r += 1
ws.cell(row=r, column=1, value="IMPORTANT CAVEATS").font = Font(name=FONT, bold=True, size=11, color="B5651A")
r += 1
caveats = [
    ("All data is synthetic.",
     "No real patients, sites, investigators or products. For training only."),
    ("Core designations follow SDTMIG v3.3.",
     "Always verify against the IG domain tables for a real study — they change between versions."),
    ("Dictionary coding is ILLUSTRATIVE.",
     "Real AEDECOD requires licensed MedDRA; real CMDECOD requires licensed WHODrug. "
     "The coded values here are plausible stand-ins, not authoritative dictionary output."),
    ("AEREL codelist is sponsor-defined.",
     "Values shown are upper-cased source text, not fixed CDISC CT."),
    ("LB standard units = original units in this study only.",
     "Collected units are already the standard units, so no conversion is applied. Real studies "
     "usually require conversion into --STRESU (e.g. creatinine mg/dL -> umol/L x 88.42)."),
]
for k, v in caveats:
    c = ws.cell(row=r, column=1, value=k)
    c.font = Font(name=FONT, bold=True, size=10, color="B5651A")
    c.alignment = Alignment(vertical="top", wrap_text=True)
    c.fill = WARN_FILL
    c2 = ws.cell(row=r, column=2, value=v)
    c2.font = Font(name=FONT, size=10)
    c2.alignment = Alignment(vertical="top", wrap_text=True)
    c2.fill = WARN_FILL
    ws.row_dimensions[r].height = 30
    r += 1

ws.column_dimensions["A"].width = 42
ws.column_dimensions["B"].width = 95

# ============================================================ DOMAIN INDEX
ws = wb.create_sheet("Domain Index")
title_block(ws, "Domain index",
            "Variable counts are live formulas counting the rows on each domain sheet.")
domains = [
    ("DM", "Demographics", "Special Purpose", "One row per subject", "dm_raw + ex_raw + ds_raw", "sdtm/dm.csv", 8),
    ("DS", "Disposition", "Events", "One row per disposition record (3 per subject)", "dm_raw + ds_raw", "sdtm/ds.csv", 24),
    ("EX", "Exposure", "Interventions", "One row per subject per dosing period", "ex_raw.csv", "sdtm/ex.csv", 8),
    ("AE", "Adverse Events", "Events", "One row per event per subject", "ae_raw.csv", "sdtm/ae.csv", 10),
    ("SUPPAE", "Supplemental Qualifiers for AE", "Relationship", "One row per qualifier value per AE record", "derived from sdtm/ae.csv", "sdtm/suppae.csv", 10),
    ("CM", "Concomitant Medications", "Interventions", "One row per medication per subject", "cm_raw.csv", "sdtm/cm.csv", 8),
    ("VS", "Vital Signs", "Findings", "One row per test result (wide -> tall)", "vs_raw.csv", "sdtm/vs.csv", 128),
    ("LB", "Laboratory", "Findings", "One row per test per visit", "lb_raw.csv", "sdtm/lb.csv", 48),
]
#  The row counts above are hardcoded, so they can go stale the moment the data
#  changes - which is exactly what happened to AE (declared 9, actually 10) and
#  survived into a slide. Fail the build rather than ship a wrong number.
import csv as _csv
_drift = []
for _d in domains:
    _path = os.path.join(HERE, _d[5])
    if os.path.exists(_path):
        with open(_path) as _fh:
            _actual = sum(1 for _ in _csv.DictReader(_fh))
        if _actual != _d[6]:
            _drift.append(f"{_d[0]}: spec says {_d[6]}, {_d[5]} has {_actual}")
if _drift:
    raise SystemExit("STALE ROW COUNTS in the domain index:\n  " + "\n  ".join(_drift))

rows = [[d[0], d[1], d[2], d[3], d[4], d[5], d[6], None] for d in domains]
write_table(ws, 4,
            ["Domain", "Name", "Observation Class", "Structure", "Source file(s)",
             "Target file", "Target rows", "Variables"],
            rows, [10, 26, 18, 38, 26, 16, 12, 11])
# live formula: count variable rows on each domain sheet
for i, d in enumerate(domains):
    ws.cell(row=5 + i, column=8, value=f"=COUNTA({d[0]}!B:B)-1").font = Font(name=FONT, size=10)

# ============================================================ GLOBAL RULES
ws = wb.create_sheet("Global Rules")
title_block(ws, "Global derivation rules",
            "These apply to every domain. Get them right once and most of the mapping follows.")
rules = [
    ("USUBJID", "Unique Subject Identifier",
     'USUBJID = STUDYID || "-" || SITEID || "-" || SUBJID   ->   ABC-01-01-001',
     "SUBJID is unique only WITHIN a site (subject 001 exists at both sites). Read SITEID/SUBJID "
     "as CHARACTER or leading zeros are lost (001 -> 1)."),
    ("ISO 8601 dates", "All --DTC variables",
     "YYYY-MM-DD, stored as CHARACTER. NO raw date is ISO — raw formats are DD-MMM-YYYY (dm/ds/ex/vs/lb) and a MIX of DD/MM/YYYY + DD-Mon-YYYY (ae/cm).",
     "A blank end date means ONGOING — leave null. Never invent a date. 01/03/2024 is ambiguous; "
     "the data dictionary states DD/MM/YYYY. DD-MMM-YYYY text does NOT sort chronologically — convert before min/max."),
    ("--SEQ", "Sequence Number",
     "Sequential 1,2,3... within USUBJID within domain, after sorting into a deterministic order.",
     "USUBJID + --SEQ must be unique. Sort orders used: AE/CM by start date then term; "
     "VS/LB by VISITNUM then test, where TEST ORDER IS THE ORDER THE TESTS APPEAR IN THE "
     "RAW FILE - VS: SYSBP, DIABP, PULSE, TEMP, HEIGHT, WEIGHT; LB: HGB, HCT, WBC, PLAT, "
     "ALT, CREAT. Stating this matters: 'by test' alone is ambiguous (alphabetical and "
     "controlled-terminology order both differ), and two programmers would produce "
     "different --SEQ from the same data. DM has NO --SEQ."),
    ("--DY", "Study Day",
     "If --DTC >= RFSTDTC:  --DY = (--DTC - RFSTDTC) + 1\n"
     "If --DTC <  RFSTDTC:  --DY = (--DTC - RFSTDTC)      [negative]",
     "THERE IS NO DAY 0. Day 1 is the day of first dose; the day before is Day -1. "
     "RFSTDTC comes from EX (first dose)."),
    ("Controlled Terminology", "Coded variables",
     "Trim whitespace, normalise case, then map to the CDISC codelist exactly.",
     "Match spelling and case exactly. Production code should FAIL LOUDLY on an unrecognised "
     "value rather than passing text through."),
]
write_table(ws, 4, ["Rule", "Applies to", "Definition", "Notes / gotchas"],
            [list(x) for x in rules], [22, 26, 62, 68])
for r_ in range(5, 5 + len(rules)):
    ws.row_dimensions[r_].height = 58

# ============================================================ DOMAIN SHEETS
HDRS = ["#", "SDTM Variable", "SDTM Label", "Type", "Core", "Origin",
        "Source Dataset", "Source Variable", "Mapping / Derivation Rule",
        "CT Codelist", "Notes"]
WIDTHS = [5, 16, 34, 7, 7, 12, 15, 20, 58, 14, 44]

DM = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","dm_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "DM"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","dm_raw","SITEID, SUBJID",'STUDYID || "-" || SITEID || "-" || SUBJID',"","Keep IDs as character"),
    ("SUBJID","Subject Identifier for the Study","Char","Req","Collected","dm_raw","SUBJID","As collected (site-local id)","","Not unique across sites"),
    ("RFSTDTC","Subject Reference Start Date/Time","Char","Exp","Derived","ex_raw","EXSTDTC","min(EXSTDTC) per subject = first dose date","","DEFINES STUDY DAY 1 for the whole study"),
    ("RFENDTC","Subject Reference End Date/Time","Char","Exp","Derived","ex_raw","EXENDTC","max(EXENDTC) per subject = last dose date","",""),
    ("RFXSTDTC","Date/Time of First Study Treatment","Char","Exp","Derived","ex_raw","EXSTDTC","Same as RFSTDTC","",""),
    ("RFXENDTC","Date/Time of Last Study Treatment","Char","Exp","Derived","ex_raw","EXENDTC","Same as RFENDTC","",""),
    ("RFICDTC","Date/Time of Informed Consent","Char","Exp","Collected","dm_raw","RFICDTC","Convert to ISO 8601","","Reference date for AGE; also a DS protocol milestone"),
    ("RFPENDTC","Date/Time of End of Participation","Char","Exp","Collected","ds_raw","EOSDT","Convert to ISO 8601","","From the DISPOSITION form — NOT demographics"),
    ("DTHDTC","Date/Time of Death","Char","Exp","Collected","","","Null — no deaths in this study","",""),
    ("DTHFL","Subject Death Flag","Char","Exp","Derived","","","Null — no deaths in this study","NY",""),
    ("SITEID","Study Site Identifier","Char","Req","Collected","dm_raw","SITEID","As collected","","Character — preserve leading zero"),
    ("AGE","Age","Num","Exp","Derived","dm_raw","BRTHDTC, RFICDTC","Completed years from BRTHDTC to RFICDTC","","Edge case: born 1969-05-14, consent 2024-02-20 -> 54 not 55"),
    ("AGEU","Age Units","Char","Exp","Assigned","","",'Literal "YEARS"',"AGEU",""),
    ("SEX","Sex","Char","Req","Collected","dm_raw","SEX","CT lookup: 1 -> M, 2 -> F","SEX","EDC stores a numeric code"),
    ("RACE","Race","Char","Exp","Collected","dm_raw","RACE","Trim + upper-case, then map to CT","RACE","Raw is mixed case with a trailing space"),
    ("ETHNIC","Ethnicity","Char","Perm","Collected","dm_raw","ETHNIC","Upper-case, then map to CT","ETHNIC",""),
    ("ARMCD","Planned Arm Code","Char","Req","Derived","dm_raw","ARM","Drug A -> A ; Placebo -> P","","Max 20 chars, no spaces"),
    ("ARM","Description of Planned Arm","Char","Req","Collected","dm_raw","ARM","As collected","",""),
    ("ACTARMCD","Actual Arm Code","Char","Req","Derived","dm_raw","ARM","Same as ARMCD","","As-treated = as-planned in this study"),
    ("ACTARM","Description of Actual Arm","Char","Req","Derived","dm_raw","ARM","Same as ARM","","Would differ if a subject were mis-dosed"),
    ("COUNTRY","Country","Char","Req","Collected","dm_raw","COUNTRY","As collected","COUNTRY","Already ISO 3166-1 alpha-3"),
]
DS = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","dm_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "DS"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","dm_raw","SITEID, SUBJID","See Global Rules","",""),
    ("DSSEQ","Sequence Number","Num","Req","Derived","","","Sequential per subject, ordered by DSSTDTC then DSCAT","","3 records per subject in this study"),
    ("DSTERM","Reported Term for the Disposition Event","Char","Req","Collected","ds_raw","EOSSTAT, EOSREAS",'Descriptive term, e.g. "Discontinued: Adverse event"',"","Topic variable"),
    ("DSDECOD","Standardized Disposition Term","Char","Req","Derived","ds_raw","EOSSTAT, EOSREAS","Map to CT — see Controlled Terminology sheet","NCOMPLT / DSDECOD",""),
    ("DSCAT","Category for Disposition Event","Char","Perm","Derived","","",'"PROTOCOL MILESTONE" or "DISPOSITION EVENT"',"DSCAT","Distinguishes milestones from the exit record"),
    ("DSSTDTC","Start Date/Time of Disposition Event","Char","Exp","Collected","dm_raw / ds_raw","RFICDTC, RANDDTC, EOSDT","Consent -> RFICDTC; Randomized -> RANDDTC; exit -> EOSDT","",""),
    ("DSSTDY","Study Day of Start of Disposition Event","Num","Perm","Derived","","","See Global Rules (--DY)","","Consent is negative; randomization = Day 1"),
]
EX = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","ex_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "EX"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","ex_raw","SITEID, SUBJID","See Global Rules","",""),
    ("EXSEQ","Sequence Number","Num","Req","Derived","","","1 — single dosing period per subject","","See Global Rules"),
    ("EXTRT","Name of Treatment","Char","Req","Collected","ex_raw","EXTRT","As collected (Drug A / Placebo)","","Topic variable"),
    ("EXDOSE","Dose per Administration","Num","Exp","Collected","ex_raw","EXDOSE","As collected (50, or 0 for placebo)","",""),
    ("EXDOSU","Dose Units","Char","Exp","Collected","ex_raw","EXDOSU",'"mg"',"UNIT",""),
    ("EXDOSFRQ","Dosing Frequency per Interval","Char","Perm","Collected","ex_raw","EXFREQ","As collected (QD)","FREQ","NOTE THE RENAME: raw EXFREQ -> SDTM EXDOSFRQ"),
    ("EXROUTE","Route of Administration","Char","Perm","Collected","ex_raw","EXROUTE",'"ORAL"',"ROUTE",""),
    ("EXSTDTC","Start Date/Time of Treatment","Char","Exp","Collected","ex_raw","EXSTDTC","Convert to ISO 8601","",""),
    ("EXENDTC","End Date/Time of Treatment","Char","Perm","Collected","ex_raw","EXENDTC","Convert to ISO 8601","",""),
    ("EXSTDY","Study Day of Start of Treatment","Num","Perm","Derived","","","See Global Rules (--DY)","","Always 1 — useful self-check"),
    ("EXENDY","Study Day of End of Treatment","Num","Perm","Derived","","","See Global Rules (--DY)","",""),
    ("(EOSOTH)","'If Other, specify' — NOT an SDTM variable","Char","n/a","Collected","ds_raw","EOSOTH","Not submitted. Feeds the verbatim DSTERM when the reason is Other","","Blank for all subjects here"),
    ("(VSND)","Assessments not performed? — NOT an SDTM variable","Char","n/a","Collected","vs_raw","VSND","Not submitted. A Y would drive VSSTAT=NOT DONE and VSREASND","","N for all records here"),
    ("(EXINTP)","Dosing interrupted? — NOT an SDTM variable","Char","n/a","Collected","ex_raw","EXINTP","Not submitted. Y = split into one EX record per continuous dosing period (EXSEQ 1,2,3...)","","All N in this study, so 1 record per subject"),
]
AE = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","ae_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "AE"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","ae_raw","SITEID, SUBJID","See Global Rules","",""),
    ("AESEQ","Sequence Number","Num","Req","Derived","","","Sequential per subject, ordered by AESTDTC then AETERM","","See Global Rules"),
    ("AETERM","Reported Term for the Adverse Event","Char","Req","Collected","ae_raw","AETERM","VERBATIM, exactly as reported — never cleaned","","Topic variable"),
    ("AEDECOD","Dictionary-Derived Term","Char","Req","Derived","ae_raw","AETERM","Dictionary preferred term","","ILLUSTRATIVE — real coding needs licensed MedDRA"),
    ("AESEV","Severity/Intensity","Char","Perm","Collected","ae_raw","AESEV","Upper-case -> CT","AESEV","MILD / MODERATE / SEVERE"),
    ("AESER","Serious Event","Char","Exp","Collected","ae_raw","AESER","No/N -> N ; Yes -> Y","NY","Both 'No' and 'N' appear in raw"),
    ("AEREL","Causality","Char","Exp","Collected","ae_raw","AEREL","Upper-case source text","","Codelist commonly SPONSOR-DEFINED"),
    ("AEOUT","Outcome of Adverse Event","Char","Perm","Collected","ae_raw","AEOUT","Decode numeric code 1-5 to its CT term","OUT","Raw is a CRF dropdown CODE, not text — never pass the number through"),
    ("AESTDTC","Start Date/Time of Adverse Event","Char","Exp","Collected","ae_raw","AESTDT","Convert mixed formats to ISO 8601","","Two formats present"),
    ("AEENDTC","End Date/Time of Adverse Event","Char","Perm","Collected","ae_raw","AEENDT","Convert to ISO 8601","","BLANK = ONGOING — leave null"),
    ("AESTDY","Study Day of Start of Event","Num","Perm","Derived","","","See Global Rules (--DY)","",""),
    ("AEENDY","Study Day of End of Event","Num","Perm","Derived","","","See Global Rules (--DY)","","Null when the event is ongoing"),
]
CM = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","cm_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "CM"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","cm_raw","SITEID, SUBJID","See Global Rules","",""),
    ("CMSEQ","Sequence Number","Num","Req","Derived","","","Sequential per subject, ordered by CMSTDTC then CMTRT","","See Global Rules"),
    ("CMTRT","Reported Name of Drug, Med, or Therapy","Char","Req","Collected","cm_raw","CMTRT","VERBATIM medication name","","Topic variable"),
    ("CMDECOD","Standardized Medication Name","Char","Perm","Derived","cm_raw","CMTRT","Dictionary term","","ILLUSTRATIVE — real coding needs licensed WHODrug"),
    ("CMINDC","Indication","Char","Perm","Collected","cm_raw","CMINDC","As collected","",""),
    ("CMDOSE","Dose per Administration","Num","Perm","Collected","cm_raw","CMDOSE","As collected","",""),
    ("CMDOSU","Dose Units","Char","Perm","Collected","cm_raw","CMDOSU","mg / IU / %","UNIT",""),
    ("CMDOSFRQ","Dosing Frequency per Interval","Char","Perm","Collected","cm_raw","CMFREQ","As collected (QD / BID / PRN)","FREQ","NOTE THE RENAME: raw CMFREQ -> SDTM CMDOSFRQ"),
    ("CMROUTE","Route of Administration","Char","Perm","Collected","cm_raw","CMROUTE","ORAL / TOPICAL","ROUTE",""),
    ("CMSTDTC","Start Date/Time of Medication","Char","Exp","Collected","cm_raw","CMSTDT","Convert mixed formats to ISO 8601","",""),
    ("CMENDTC","End Date/Time of Medication","Char","Perm","Collected","cm_raw","CMENDT","Convert to ISO 8601","","BLANK = ONGOING — leave null"),
    ("CMSTDY","Study Day of Start of Medication","Num","Perm","Derived","","","See Global Rules (--DY)","","NEGATIVE for meds started before first dose"),
    ("CMENDY","Study Day of End of Medication","Num","Perm","Derived","","","See Global Rules (--DY)","",""),
]
VS = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","vs_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "VS"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","vs_raw","SITEID, SUBJID","See Global Rules","",""),
    ("VSSEQ","Sequence Number","Num","Req","Derived","","","Sequential per subject, ordered by VISITNUM then test in raw-file order (SYSBP, DIABP, PULSE, TEMP, HEIGHT, WEIGHT)","","See Global Rules"),
    ("VSTESTCD","Vital Signs Test Short Name","Char","Req","Derived","vs_raw","column name","Column name -> CT code (SYSBP, DIABP, PULSE, TEMP, HEIGHT, WEIGHT)","VSTESTCD","Topic variable — comes from the COLUMN NAME"),
    ("VSTEST","Vital Signs Test Name","Char","Req","Derived","vs_raw","column name","Long name from CT","VSTEST",""),
    ("VSORRES","Result or Finding in Original Units","Char","Exp","Collected","vs_raw","cell value","Result AS COLLECTED (character)","",""),
    ("VSORRESU","Original Units","Char","Exp","Protocol","","","mmHg / beats/min / C / cm / kg","UNIT","Per test — from the protocol"),
    ("VSSTRESC","Character Result in Std Format","Char","Exp","Derived","","","Same as VSORRES","","No conversion needed in this study"),
    ("VSSTRESN","Numeric Result in Std Units","Num","Exp","Derived","","","VSORRES as numeric","",""),
    ("VSSTRESU","Standard Units","Char","Exp","Derived","","","Same as VSORRESU","UNIT","Collected units already standard"),
    ("VSBLFL","Baseline Flag","Char","Perm","Derived","vs_raw","VISIT",'"Y" at the BASELINE visit',"NY","Last assessment on/before first dose"),
    ("VISITNUM","Visit Number","Num","Exp","Derived","vs_raw","VISIT","SCREENING=1, BASELINE=2, WEEK 4=4","",""),
    ("VISIT","Visit Name","Char","Perm","Collected","vs_raw","VISIT","As collected","",""),
    ("VSDTC","Date/Time of Measurements","Char","Exp","Collected","vs_raw","VSDT","Convert to ISO 8601","",""),
    ("VSDY","Study Day of Measurements","Num","Perm","Derived","","","See Global Rules (--DY)","","Negative at SCREENING"),
]
SUPPAE = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","","",'Constant "ABC-01"',"",""),
    ("RDOMAIN","Related Domain Abbreviation","Char","Req","Assigned","","",'Literal "AE" — the domain this qualifies',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","sdtm/ae.csv","USUBJID","Copied from the parent AE record","",""),
    ("IDVAR","Identifying Variable","Char","Exp","Assigned","","",'Literal "AESEQ" — how we point at the parent row',"",""),
    ("IDVARVAL","Identifying Variable Value","Char","Exp","Derived","sdtm/ae.csv","AESEQ","The parent record's AESEQ value","",""),
    ("QNAM","Qualifier Variable Name","Char","Req","Assigned","","",'Literal "AETRTEM"',"","Must NOT duplicate an existing AE variable"),
    ("QLABEL","Qualifier Variable Label","Char","Exp","Assigned","","",'Literal "Treatment Emergent Flag"',"",""),
    ("QVAL","Data Value","Char","Req","Derived","sdtm/ae.csv","AESTDY","Y if AESTDY >= 1 (on/after first dose), else N","NY","All Y in ABC-01 — see the spec caveat"),
    ("QORIG","Origin","Char","Exp","Assigned","","",'Literal "DERIVED"',"",""),
    ("QEVAL","Evaluator","Char","Perm","Assigned","","","Blank — derived, not assessed by a person","",""),
]
LB = [
    ("STUDYID","Study Identifier","Char","Req","Assigned","lb_raw","STUDYID",'Constant "ABC-01"',"",""),
    ("DOMAIN","Domain Abbreviation","Char","Req","Assigned","","",'Literal "LB"',"",""),
    ("USUBJID","Unique Subject Identifier","Char","Req","Derived","lb_raw","SITEID, SUBJID","See Global Rules","",""),
    ("LBSEQ","Sequence Number","Num","Req","Derived","","","Sequential per subject, ordered by VISITNUM then test in raw-file order (HGB, HCT, WBC, PLAT, ALT, CREAT)","","See Global Rules"),
    ("LBTESTCD","Lab Test or Examination Short Name","Char","Req","Derived","lb_raw","LBTEST","Map test name -> CT code","LBTESTCD","Topic variable"),
    ("LBTEST","Lab Test or Examination Name","Char","Req","Derived","lb_raw","LBTEST","CT long name","LBTEST",'"White Blood Cells" -> "Leukocytes"'),
    ("LBCAT","Category for Lab Test","Char","Perm","Derived","lb_raw","LBTEST","HEMATOLOGY or CHEMISTRY","",""),
    ("LBORRES","Result or Finding in Original Units","Char","Exp","Collected","lb_raw","LBORRES","As collected","",""),
    ("LBORRESU","Original Units","Char","Exp","Collected","lb_raw","LBORRESU","As collected","UNIT",""),
    ("LBORNRLO","Reference Range Lower Limit (orig)","Char","Perm","Collected","lb_raw","LBORNRLO","As collected","",""),
    ("LBORNRHI","Reference Range Upper Limit (orig)","Char","Perm","Collected","lb_raw","LBORNRHI","As collected","",""),
    ("LBSTRESC","Character Result in Std Format","Char","Exp","Derived","","","Same as LBORRES","",""),
    ("LBSTRESN","Numeric Result in Std Units","Num","Exp","Derived","","","LBORRES as numeric","",""),
    ("LBSTRESU","Standard Units","Char","Exp","Derived","","","Same as LBORRESU","UNIT","NO CONVERSION in this study — see Cover caveats"),
    ("LBSTNRLO","Reference Range Lower Limit (std)","Num","Perm","Derived","","","Same as LBORNRLO","",""),
    ("LBSTNRHI","Reference Range Upper Limit (std)","Num","Perm","Derived","","","Same as LBORNRHI","",""),
    ("LBNRIND","Reference Range Indicator","Char","Perm","Derived","","","LOW if result < low ; HIGH if > high ; else NORMAL","NRIND","1 HIGH in this study (ALT 72 U/L, subject 01-003 Week 4)"),
    ("LBBLFL","Baseline Flag","Char","Perm","Derived","lb_raw","VISIT",'"Y" at the BASELINE visit',"NY",""),
    ("VISITNUM","Visit Number","Num","Exp","Derived","lb_raw","VISIT","BASELINE=2, WEEK 4=4","",""),
    ("VISIT","Visit Name","Char","Perm","Collected","lb_raw","VISIT","As collected","",""),
    ("LBDTC","Date/Time of Specimen Collection","Char","Exp","Collected","lb_raw","LBDT","Convert to ISO 8601","",""),
    ("LBDY","Study Day of Specimen Collection","Num","Perm","Derived","","","See Global Rules (--DY)","",""),
]

for name, spec, note in [
    ("DM", DM, "Special Purpose · one row per subject · NO --SEQ variable"),
    ("DS", DS, "Events · one row per disposition record · 2 protocol milestones + 1 disposition event per subject"),
    ("EX", EX, "Interventions · one row per subject per dosing period"),
    ("AE", AE, "Events · one row per event per subject"),
    ("SUPPAE", SUPPAE, "Supplemental Qualifiers · one row per qualifier value · AETRTEM = Treatment Emergent Flag"),
    ("CM", CM, "Interventions · one row per medication per subject"),
    ("VS", VS, "Findings · one row per test result · raw is WIDE and must be transposed (24 rows -> 128)"),
    ("LB", LB, "Findings · one row per test per visit · raw is already tall"),
]:
    ws = wb.create_sheet(name)
    title_block(ws, f"{name} — variable-level mapping", note)
    rows = [[i + 1] + list(v) for i, v in enumerate(spec)]
    write_table(ws, 4, HDRS, rows, WIDTHS)

# ============================================================ CONTROLLED TERMINOLOGY
ws = wb.create_sheet("Controlled Terminology")
title_block(ws, "Controlled Terminology — value-level mappings",
            "Trim whitespace and normalise case before matching. Match CT spelling and case exactly.")
ct = [
    ("SEX","DM.SEX","1","M","EDC numeric code"),
    ("SEX","DM.SEX","2","F","EDC numeric code"),
    ("RACE","DM.RACE","White  /  'White ' (trailing space)","WHITE","Trim then upper-case"),
    ("RACE","DM.RACE","Asian  /  asian","ASIAN",""),
    ("RACE","DM.RACE","black or african american  /  Black or African American","BLACK OR AFRICAN AMERICAN",""),
    ("ETHNIC","DM.ETHNIC","Not Hispanic or Latino","NOT HISPANIC OR LATINO",""),
    ("ETHNIC","DM.ETHNIC","Hispanic or Latino","HISPANIC OR LATINO",""),
    ("ETHNIC","DM.ETHNIC","Unknown","UNKNOWN","A recorded value, NOT a missing value"),
    ("(arm)","DM.ARMCD","Drug A","A","Max 20 chars, no spaces"),
    ("(arm)","DM.ARMCD","Placebo","P",""),
    ("DSCAT","DS.DSCAT","(consent / randomization records)","PROTOCOL MILESTONE","Planned checkpoints every subject passes"),
    ("DSCAT","DS.DSCAT","(end-of-study record)","DISPOSITION EVENT","How the subject left the study"),
    ("DSDECOD","DS.DSDECOD","EOSSTAT = Completed","COMPLETED",""),
    ("DSDECOD","DS.DSDECOD","EOSSTAT = Discontinued + EOSREAS = Adverse event","ADVERSE EVENT","Reason drives DSDECOD, not the status"),
    ("DSDECOD","DS.DSDECOD","(informed consent milestone)","INFORMED CONSENT OBTAINED","Date from dm_raw.RFICDTC"),
    ("DSDECOD","DS.DSDECOD","(randomization milestone)","RANDOMIZED","Date from dm_raw.RANDDTC"),
    ("AESEV","AE.AESEV","mild / Mild","MILD",""),
    ("AESEV","AE.AESEV","moderate / Moderate","MODERATE",""),
    ("AESEV","AE.AESEV","severe","SEVERE",""),
    ("NY","AE.AESER","No / N","N",""),
    ("NY","AE.AESER","Yes","Y",""),
    ("OUT","AE.AEOUT","1","RECOVERED/RESOLVED","CRF dropdown code"),
    ("OUT","AE.AEOUT","2","RECOVERING/RESOLVING","CRF dropdown code"),
    ("OUT","AE.AEOUT","3","NOT RECOVERED/NOT RESOLVED","CRF dropdown code"),
    ("OUT","AE.AEOUT","4","FATAL","CRF dropdown code (not used in this study)"),
    ("OUT","AE.AEOUT","5","UNKNOWN","CRF dropdown code (not used in this study)"),
    ("(sponsor)","AE.AEREL","Related / Not related / Possibly related / Unlikely related","(upper-cased source text)","Codelist commonly SPONSOR-DEFINED, not fixed CDISC CT"),
    ("VSTESTCD","VS.VSTESTCD/VSTEST","SYSBP column","SYSBP / Systolic Blood Pressure",""),
    ("VSTESTCD","VS.VSTESTCD/VSTEST","DIABP column","DIABP / Diastolic Blood Pressure",""),
    ("VSTESTCD","VS.VSTESTCD/VSTEST","PULSE column","PULSE / Pulse Rate",""),
    ("VSTESTCD","VS.VSTESTCD/VSTEST","TEMP column","TEMP / Temperature","Celsius"),
    ("VSTESTCD","VS.VSTESTCD/VSTEST","HEIGHT column","HEIGHT / Height","SCREENING only"),
    ("VSTESTCD","VS.VSTESTCD/VSTEST","WEIGHT column","WEIGHT / Weight",""),
    ("LBTESTCD","LB.LBTESTCD/LBTEST","Hemoglobin","HGB / Hemoglobin","HEMATOLOGY"),
    ("LBTESTCD","LB.LBTESTCD/LBTEST","Hematocrit","HCT / Hematocrit","HEMATOLOGY"),
    ("LBTESTCD","LB.LBTESTCD/LBTEST","White Blood Cells","WBC / Leukocytes","HEMATOLOGY — NOTE the CT name differs from the collected name"),
    ("LBTESTCD","LB.LBTESTCD/LBTEST","Platelets","PLAT / Platelets","HEMATOLOGY"),
    ("LBTESTCD","LB.LBTESTCD/LBTEST","Alanine Aminotransferase","ALT / Alanine Aminotransferase","CHEMISTRY"),
    ("LBTESTCD","LB.LBTESTCD/LBTEST","Creatinine","CREAT / Creatinine","CHEMISTRY"),
]
write_table(ws, 4, ["Codelist", "Applies to", "Raw value(s)", "SDTM value", "Notes"],
            [list(x) for x in ct], [14, 22, 56, 40, 52])

# ============================================================ QC CHECKS
ws = wb.create_sheet("QC Checks")
title_block(ws, "QC checks",
            "Run these against your own output. The reference datasets in /data/sdtm pass all of them.")
qc = [
    ("Identifiers","USUBJID unique in DM","8 rows, 8 distinct USUBJID"),
    ("Identifiers","USUBJID + --SEQ unique","True in every domain (AE, CM, EX, VS, LB)"),
    ("Identifiers","DM has no DMSEQ","DM is one row per subject — no sequence variable"),
    ("Study day","Any --DY equal to 0","NONE — there is no Day 0"),
    ("Study day","EXSTDY","1 for every subject (first dose defines Day 1)"),
    ("Study day","SCREENING VSDY","Negative"),
    ("Study day","BASELINE VSDY","1"),
    ("Dates","All *DTC values","Match YYYY-MM-DD"),
    ("Dates","Ongoing AEs","2 rows with null AEENDTC (and null AEENDY)"),
    ("Structure","VS row count","128 (8 subj x [6 screening + 5 baseline + 5 week 4])"),
    ("Structure","HEIGHT records","SCREENING only — 8 rows"),
    ("Values","LBNRIND = HIGH","Exactly 1 (subject ABC-01-01-003, Week 4, ALT 72 U/L)"),
    ("Values","Required variables populated","No nulls in STUDYID, DOMAIN, USUBJID, --SEQ, topic variables"),
    ("Values","CT conformance","Every coded value appears in its codelist"),
]
write_table(ws, 4, ["Area", "Check", "Expected result"], [list(x) for x in qc], [16, 42, 72])

wb.save(OUT)
print("wrote", OUT)
print("sheets:", ", ".join(wb.sheetnames))
